### ISSUE TITLE
SSL error 1407742E during emsdk install --latest

### ISSUE THREAD

**Issue by Inreal** [juj/emsdk#133]
Running on Windows 10. The commands and installation routine worked for the same installation package a few days ago. Now it gives the following SSL error:

```Installing SDK 'sdk-1.37.9-64bit'..
Installing tool 'clang-e1.37.9-64bit'..
The contents of file 'llvm/tag/win_64bit/emscripten-llvm-e1.37.9.zip' already exist in destination 'C:/Emscripten/clang/e1.37.9_64bit', skipping.
Done installing tool 'clang-e1.37.9-64bit'.
Installing tool 'node-4.1.1-64bit'..
The contents of file 'node_4.1.1_64bit.zip' already exist in destination 'C:/Emscripten/node/4.1.1_64bit', skipping.
Done installing tool 'node-4.1.1-64bit'.
Installing tool 'python-2.7.5.3-64bit'..
The contents of file 'python_2.7.5.3_64bit.zip' already exist in destination 'C:/Emscripten/python/2.7.5.3_64bit', skipping.
Done installing tool 'python-2.7.5.3-64bit'.
Installing tool 'java-7.45-64bit'..
The contents of file 'portable_jre_7_update_45_64bit.zip' already exist in destination 'C:/Emscripten/java/7.45_64bit', skipping.
Done installing tool 'java-7.45-64bit'.
Installing tool 'emscripten-1.37.9'..
Traceback (most recent call last):
  File "C:\Emscripten\\emsdk", line 2149, in <module>
    sys.exit(main())
  File "C:\Emscripten\\emsdk", line 2132, in main
    success = tool.install()
  File "C:\Emscripten\\emsdk", line 1229, in install
    success = tool.install()
  File "C:\Emscripten\\emsdk", line 1244, in install
    success = download_and_unzip(url, self.installation_path(), download_even_if_exists, filename_prefix=self.zipfile_prefix if hasattr(self, 'zipfile_prefix') else '')
  File "C:\Emscripten\\emsdk", line 850, in download_and_unzip
    dst_file = download_file(urljoin(emsdk_packages_url, zipfile), 'zips/', download_even_if_exists, filename_prefix)
  File "C:\Emscripten\\emsdk", line 416, in download_file
    u = urlopen(url)
  File "C:\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>
```

I guess it's related to the hosting setup?

**Comment by hpohl** [comment]
Can confirm. I think it's because of an outdated python.

**Comment by segevfiner** [comment]
Seems like GitHub hardened their SSL/TLS configuration. The bundled Python is definitely old and has an outdated OpenSSL:
```bat
>emsdk\python\2.7.5.3_64bit\python.exe
Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 0.9.8y 5 Feb 2013'
>>>
```

**Comment by juj** [comment]
Thanks for reporting, this is fixed in https://github.com/juj/emsdk/commit/4c8ea1b10be7ab59ec0bb5a63934372cb4c2bcff.

**Comment by segevfiner** [comment]
@juj I just tried a fresh install (`emsdk update && emsdk install latest`) and it didn't try to update Python and failed with the SSL error.
