### ISSUE TITLE
"ERROR:root:cwrap]': No such file or directory"

### ISSUE THREAD

**Issue by DragonOsman** [juj/emsdk#174]
I tried to follow the `int_sqrt` example here: https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html but I got an error saying 
```
ERROR:root:cwrap]': No such file or directory ("cwrap]'" was expected to be an input file, based on the commandline arguments provided)
```
Could someone please help me out here?

**Comment by kripken** [comment]
Probably an escaping issue or a typo in the command you wrote. What was the command, and in what shell?

**Comment by kripken** [comment]
(By the error message, `("cwrap]'"`, I suspect you need to move the quotes around, to `("cwrap"]'`)

**Comment by DragonOsman** [comment]
So no one is able to help me out?  

Again, I followed the aforementioned tutorial and called `cwrap` exactly as it says and I still got that error.  I need help on this.

Also, there's that other issue I opened about porting my web server application to WebAssembly as a module to use on the backend through Node.  The code for the app is [here](https://github.com/DragonOsman/currency_converter).  I also wrote an asynchronous version of the code, but on that one I'm having trouble with making the client code asynchronous because of the code in `cache_storage::query()` that I need to convert to be asynchronous.  

And because this uses Beast which is based of ASIO (which doesn't support WebAssembly), I need to know how to port ASIO to WebAssembly as well.

**Comment by kripken** [comment]
I don't know much about WSL, but this seems like an escaping issue. Might be worth trying all the other possibilities, like `-s 'X=["y"]'` for example (note `'` are around the key, the equals, and the value).

**Comment by DragonOsman** [comment]
Just now, I again tried to run this same command:
```
emcc tests/hello_function.cpp -o function.html -s EXPORTED_FUNCTIONS='["_int_sqrt"]' -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]'
```
exactly as documented in the tutorial, but I got this same error again:
```
ERROR:root:cwrap]': No such file or directory ("cwrap]'" was expected to be an input file, based on the commandline arguments provided)
```
I'm sure I didn't make any mistakes.  I just copy-pasted the command as is from the tutorial [here](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html).  There shouldn't be any mistakes.  

Also, just now, I tried to build my `currency_converter.cpp` app with this command: 
```
em++ -std=c++17 -Wall -pedantic -D variant_CONFIG_SELECT_VARIANT=variant_VARIANT_NONSTD -s DISABLE_EXCEPTION_CATCHING=0 -I C:/Jinja2Cpp/install_x64/include -I C:/json/single_include -I C:/boost_1_68_0/ -c currency_converter.cpp -L C:/Jinja2Cpp/install_x64/lib/static/jinja2cpp.lib -L C:/boost_1_68_0/lib64-msvc-14.1/libboost_system-vc141-mt-x64-1_68.lib -lpthread -o currency_converter.js
```
and it didn't generate a .wasm file.  I tried entering the command `node currency_converter.js` as well, but I got this error:
```
E:\programming\visual_studio_2017\Projects\currency_converter\currency_converter\currency_converter.js:1
(function (exports, require, module, __filename, __dirname) { BC��5
                                                                ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
And I tried to open the .js file as well.  There's nothing to show, though.  No file coming in Visual Studio.

**Comment by DragonOsman** [comment]
On second thought, It could be because I have to give special treatment to `std::shared_ptr` when trying to compile to WebAssembly.  I'll have to read again about how to do that.

Also, if I want to pass API keys as environment variables to use in my WebAssembly application, and I want to use it as a Node.js module, should I use ENV in my Node.js code like this? 
```js
Module.preRun.push(function() {ENV.my_key = "value"})
```

**Comment by hainawa** [comment]
I've met the same problem.After trying several times,I found it could be resolved by change ' to ":
emcc tests/hello_function.cpp -o function.html -s EXPORTED_FUNCTIONS="['_int_sqrt']" -s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']"

**Comment by raspiduino** [comment]
For someone who export functions in cmake, `-sEXPORTED_FUNCTIONS=['_int_sqrt'] -sEXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap']` worked for me!

See [this](https://stackoverflow.com/questions/62575726/how-to-export-c-function-in-emscripten-when-using-cmake) StackOverflow post.
