### ISSUE TITLE
My first hello.c but I encountered an error

### ISSUE THREAD

**Issue by c0debreaker** [juj/emsdk#75]
I got this when I ran `emcc hello.c -s WASM=1 -o hello.html`. What should I do?

```
build executables
save the before js
process input
cannot use WASM=1 when full asm.js validation was disabled (make sure to run in at least -O1, and look for warnings about other options that might force asm.js off)
Traceback (most recent call last):
  File "/Users/rcamara/Downloads/emsdk-portable/emscripten/1.35.0/emcc", line 1835, in <module>
    subprocess.check_call([shared.PYTHON, shared.path_from_root('third_party', 'wasm-polyfill', 'wasmator.py'), js_target, wasm_target, shared.Settings.EXPORT_NAME])
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/opt/python/bin/python2.7', '/Users/rcamara/Downloads/emsdk-portable/emscripten/1.35.0/third_party/wasm-polyfill/wasmator.py', 'hello.js', 'hello.wasm', u'Module']' returned non-zero exit status 1
 ```

**Comment by juj** [comment]
The log prints above look like it's on 1.35.0. Try updating with

    ./emsdk update
    ./emsdk update-tags
    ./emsdk list

that should show Emscripten version 1.37.12 available for install. Does that work?

**Comment by itahmid** [comment]
I have a similar issue with hello.c

Traceback (most recent call last):
  File "/usr/bin/emcc", line 52, in <module>
    from tools import shared, jsrun
  File "/usr/share/emscripten/tools/shared.py", line 442, in <module>
    USING_PNACL_TOOLCHAIN = os.path.exists(os.path.join(LLVM_ROOT, 'pnacl-clang'))
NameError: name 'LLVM_ROOT' is not defined

**Comment by juj** [comment]
The location `/usr/share/emscripten` suggests that `emsdk` was not being used to install, but your system has Emscripten sourced from `apt-get` or similar package manager? Try bootstrapping to Emscripten with something like

```bash
wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
tar -xvf emsdk-portable.tar.gz
cd emsdk-portable
./emsdk list # this should show up "sdk-1.37.13-64bit" as latest version
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh
cd $EMSCRIPTEN
emcc tests/hello_world.c -s WASM=1  -o hello_world.js
node hello_world.js
```

**Comment by c0debreaker** [comment]
I'll try that

**Comment by mlugo2** [comment]
I'm stilling having the same problem as itahmid:

Traceback (most recent call last):
  File "/usr/bin/emcc", line 54, in <module>
    from tools import shared, jsrun, system_libs
  File "/usr/share/emscripten/tools/shared.py", line 476, in <module>
    USING_PNACL_TOOLCHAIN = os.path.exists(os.path.join(LLVM_ROOT, 'pnacl-clang'))
NameError: name 'LLVM_ROOT' is not defined

**Comment by juj** [comment]
@mlugo2: The presence of `/usr/bin/emcc` suggests that the commands in the above comment were not used, because `emcc` should not appear in `/usr/bin`? Can you try with those and post the logs if it still fails?

**Comment by c0debreaker** [comment]
Oh no, I've forgotten about this. What was I working on this? I'm very sure I was trying to study something. Hints please?

**Comment by juj** [comment]
Reads like the issue was getting Wasm compilation to working, the above steps should have good success to getting to a functional toolchain.

**Comment by c0debreaker** [comment]
I pulled the latest and reinstalled. It's working fine now. Compile of hello.c worked. However, I'm seeing an issue in my browser's console. Here is the screenshot - https://imgur.com/a/rhtT2
Also, why am I seeing the logo on the top left "Powered by"?
