### ISSUE TITLE
Error while running source /usr/lib/emsdk/emsdk_env.sh on linux

### ISSUE THREAD

**Issue by BrieucP** [juj/emsdk#83]
I installed emsdk from aur on Archlinux, then the sdk-incoming-64bit but when I run source ./usr/lib/emsdk_env.sh I got the following output
```
source /usr/lib/emsdk/emsdk_env.sh
Traceback (most recent call last):
  File "./emsdk", line 2198, in <module>
    sys.exit(main())
  File "./emsdk", line 1852, in main
    if len(sys.argv) <= 1 or sys.argv[1] == 'help' or sys.argv[1] == '--help':
TypeError: object of type 'filter' has no len()
/usr/lib/emsdk/emsdk_env.sh:.:26: aucun fichier ou dossier de ce type: ./emsdk_set_env.sh

```

**Comment by gogoprog** [comment]
For the ```TypeError: object of type 'filter' has no len()``` error : you're using python3 and this is expecting python2

**Comment by BrieucP** [comment]
Thanks,
New problem, I think still with Python,
I got the this while executing emcc -v
```                     
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.15
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/brieuc/emsdk-portable/clang/fastcomp/build_incoming_64/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/6.2.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/7.1.1
Selected GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/7.1.1
Candidate multilib: .;@m64
Selected multilib: .;@m64
**WARNING:root:could not check fastcomp: list index out of range**
INFO:root:(Emscripten: Running sanity checks)
```
But I have an alias for python2 and python -V is returning 
`Python 2.7.13`

**Comment by juj** [comment]
Fixed this in https://github.com/juj/emsdk/commit/fd087c100da863752d5a892b7b7cecfdb0523731. We don't actively support python 3 to regularly do testing on it, but it looks like after that commit emsdk is functional using python 3 as well.
