### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by asRIA** [juj/emsdk#85]
On macOS we started to observe an error when `emsdk update-tags` is performed: 
```
Traceback (most recent call last):
  File "./emsdk", line 2199, in <module>
    sys.exit(main())
  File "./emsdk", line 2103, in main
    fetch_emscripten_tags()
  File "./emsdk", line 1480, in fetch_emscripten_tags
    download_file('https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/' + os_name_for_llvm_location() + '_32bit/index.txt', 'llvm-nightlies-32bit.txt', download_even_if_exists=True)
  File "./emsdk", line 420, in download_file
    u = urlopen(url)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

```
What is cause by unaccessibility of https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/osx_32bit/index.txt

**Comment by juj** [comment]
I wonder if this was some kind of transient error. Can you try again if the error still occurs?

**Comment by asRIA** [comment]
Hi, just tested on different machine, linux this time: 
```
root@e9ee50aded49:/emsdk_portable# ./emsdk  install node-4.1.1-32bit
Installing tool 'node-4.1.1-32bit'..
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/node-v4.1.1-linux-x86.tar.gz': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Installation failed!

```

**Comment by juj** [comment]
I've tried to reproduce this on multiple different systems, but have been unable to. Which OS X version was this on? Does this happen if you reinstall from the portable installer from scratch?

**Comment by mightoz** [comment]
I am having the same issue on mac os high sierra 10.13.2. Any updates on this ?

**Comment by juj** [comment]
Sorry, currently it's unknown as to why this would be happening. What is the exact error message log that gets printed?

**Comment by mightoz** [comment]
These are the errors I am getting.

MacBook-Air:emsdk-portable Oscar$ ./emsdk update

Error downloading URL '
https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_unix_update.tar.gz':
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
(_ssl.c:590)>

Fetching all tags from Emscripten Github repository...

Done. 120 tagged releases available, latest is 1.37.33.

Fetching all tags from Binaryen Github repository...

Done. 47 tagged Binaryen releases available, latest is 1.37.33.

Fetching all precompiled Nightly versions..

Error downloading URL '
https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/osx_32bit/index.txt':
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
(_ssl.c:590)>

Error downloading URL '
https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/osx_64bit/index.txt':
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
(_ssl.c:590)>

Error downloading URL '
https://s3.amazonaws.com/mozilla-games/emscripten/packages/emscripten/nightly/linux/index.txt':
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
(_ssl.c:590)>

Fetching all precompiled tagged releases..

Error downloading URL '
https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_32bit/index.txt':
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
(_ssl.c:590)>

Error downloading URL '
https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_64bit/index.txt':
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
(_ssl.c:590)>

I am running python 2.7.14 and openssl 10.0.2j. I tried updating openssl
through brew but the problem still remains.

Best regards,
Oscar

2018-02-02 16:24 GMT+01:00 juj <notifications@github.com>:

**Comment by juj** [comment]
This thread might be relevant: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

**Comment by briancullinan** [comment]
Please copy at least something relevant because, as we know, stuff disappears off the internet without notice. 

Running `/Applications/Python\ 3.6/Install\ Certificates.command` from terminal fixed the problem for me on Mac OSX.

**Comment by brandon1525** [comment]
> Please copy at least something relevant because, as we know, stuff disappears off the internet without notice.
> 
> Running `/Applications/Python\ 3.6/Install\ Certificates.command` from terminal fixed the problem for me on Mac OSX.

This works for me, I only change the python version to 3.8 in my case, and then run again the 

`./emsdk install latest` script

**Comment by sbc100** [comment]
Fixes in #1355
