### ISSUE TITLE
UnboundLocalError: local variable 'win32api' referenced before assignment 

### ISSUE THREAD

**Issue by retyui** [juj/emsdk#99]
Output `./emsdk activate sdk-incoming-64bit binaryen-master-64bit` :
```bash
emsdk [master ≡ +0 ~2 -0 !]> ./emsdk activate sdk-incoming-64bit binaryen-master-64bit
Writing .emscripten configuration file to user home directory C:\Users\vamne/
The SDK/tool 'clang-incoming-64bit' cannot be activated since it is not installed! Skipping this tool...
The SDK/tool 'node-4.1.1-64bit' cannot be activated since it is not installed! Skipping this tool...
The SDK/tool 'python-2.7.5.3-64bit' cannot be activated since it is not installed! Skipping this tool...
The SDK/tool 'java-7.45-64bit' cannot be activated since it is not installed! Skipping this tool...
The SDK/tool 'emscripten-incoming-64bit' cannot be activated since it is not installed! Skipping this tool...
The SDK/tool 'sdk-incoming-64bit' cannot be activated since it is not installed! Skipping this tool...
The SDK/tool 'binaryen-master-64bit' cannot be activated since it is not installed! Skipping this tool...
The Emscripten configuration file C:\Users\vamne\.emscripten has been rewritten with the following contents:

import os
SPIDERMONKEY_ENGINE = ''
NODE_JS = 'node'
V8_ENGINE = ''
TEMP_DIR = 'c:/users/vamne/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

Failed to read environment variable PATH:
No module named win32api
Traceback (most recent call last):
  File "G:\web\github\emsdk\\emsdk", line 2281, in <module>
    sys.exit(main())
  File "G:\web\github\emsdk\\emsdk", line 2220, in main
    tools_to_activate = set_active_tools(tools_to_activate, permanently_activate=permanently_activate)
  File "G:\web\github\emsdk\\emsdk", line 1780, in set_active_tools
    env_string = construct_env(tools_to_activate, False)
  File "G:\web\github\emsdk\\emsdk", line 1874, in construct_env
    newpath, added_path = adjusted_path(tools_to_activate)
  File "G:\web\github\emsdk\\emsdk", line 1837, in adjusted_path
    existing_path = win_get_environment_variable('PATH', system=True)
  File "G:\web\github\emsdk\\emsdk", line 217, in win_get_environment_variable
    win32api.RegCloseKey(folder)
UnboundLocalError: local variable 'win32api' referenced before assignment
```

**Comment by AlexandreAbreu** [comment]
you need win32api to be installed: 'pip install pypiwin32'

**Comment by CharlesOkwuagwu** [comment]
@AlexandreAbreu that did not help
